Sanitized ML/DL Notebooks
MACHINE LEARNING

math_linear_algebra.ipynb
1. Cell# 17: Calculated vector norm using different method.
2. Changed cell between cell# 36 and 37 to markdown since it did not looked related to this notebook.

training_linear_models.ipynb
1. Cell# 30, 52, 53: n_iter changed to max_iter

DEEP LEARNING

convolutional_neural_networks.ipynb
1. Cell# 15: Commented 3, 4, 8, 9, 12, 13. Never seen a Python code like this before.

introduction_to_artificial_neural_networks.ipynb
1. Cell# 10, 13, 22: Commented since variables were not defined before.
2. Cell# 38: Gave proper indentation.

recurrent_neural_networks.ipynb
1. Cell# 23: Commented line 2. Was throwing error "IndexError: index 2 is out of bounds for axis 0 with size 2".
2. Cell# 119, 120: ModuleNotFoundError: No module named 'google_compute_engine'.

tensorflow.ipynb
1. Cell# 18: Commented since did not seem related to this topic.

training_deep_neural_nets.ipynb
1. Cell# 52: Changed tf.get to tf.get_default_graph(). It was throwing error "AttributeError: module 'tensorflow' has no attribute 'get'".